services:
  - type: web
    name: macro-buddy-bot
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python3 main.py
    envVars:
      - key: BOT_TOKEN
        sync: false
      - key: DATABASE_URL
        value: sqlite:///macro_buddy.db